# Generated by Django 5.1.2 on 2024-10-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Instagram_link',
            new_name='instagram_link',
        ),
    ]
